docker-compose-yaml: docker-compose.yml
routes:
  autogenerate:
    insecure: Redirect
environments:
  develop:
    routes:
      - nginx:
        - developmentsite.172.18.0.240.nip.io:
            annotations:
              nginx.ingress.kubernetes.io/permanent-redirect: https://example.com/${1}
