docker-compose-yaml: docker-compose.yml
routes:
  autogenerate:
    oauthProtected: true

environments:
  o2p:
    routes:
      - nginx:
        - o2p.172.18.0.240.sslip.io:
            oauthProtected: true
