docker-compose-yaml: docker-compose.yml

network-policies:
  # the name of the service you want to allow connections to
  - service: nginx
    organizations: 
    # this allows anything in this organization
    - name: lagoon-demo-organization
      environment-type: production
    projects: 
    # this allows any environment from example-project1 to access myservice
    - name: test-project2
