version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: nginx
    volumes:
      - ./app:/app:delegated
    ports:
      - "8080:8080"
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    labels:
      lagoon.type: redis-persistent
