version: '2'

x-volumes:
  &default-volumes
  volumes:

    - .:/app:${VOLUME_FLAGS:-delegated} ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
x-user:
  &default-user
  user: '1000'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: nginx
    ports:
      - "8080:8080"
    <<: *default-volumes
    <<: *default-user
    env_file:
      - .env.local
