version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: nginx
    volumes:
      - ./app:/app:delegated
    ports:
      - "8080:8080"
  external:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: external
      lagoon.external.service: '{"name":"nginx","project":"test-project","environment":"expose-service-example1"}'
