version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
      lagoon.service.port: 8080
      lagoon.volumes.extravol.path: /extra
    volumes:
      - ./app:/app:delegated
    ports:
      - "8080:8080"
  nginx2:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
      lagoon.service.port: 8080
      lagoon.volumes.extravol.path: /extra
    volumes:
      - ./app:/app:delegated
    ports:
      - "8081:8080"
  # mariadb:
  #   image: uselagoon/mariadb-10.11-drupal:latest
  #   labels:
  #     lagoon.type: mariadb
  #   ports:
  #     - "3306"
  #   volumes:
  #     - db:/var/lib/mysql

volumes:
  db:
  extravol:
    labels:
      lagoon.type: persistent
      lagoon.backup: false