version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic-persistent
      lagoon.service.port: 8080
      lagoon.persistent: /app/storage
    volumes:
      - ./app:/app:delegated
    ports:
      - "8080:8080"
